version: '3.1'

services:

  api:
    build: .
    command: bash -c "python manage.py makemigrations && python manage.py migrate && python manage.py runserver 0.0.0.0:8000"
    volumes:
      - .:/code/
    ports:
      - 8000:8000
    environment:
      MONGO_HOST: mongo-express
      MONGO_PORT: 8081
      MONGO_USER: root
      MONGO_PASSWORD: example
      MONGO_NAME: my_database
      MEMCACHED_LOCATION: cache

#  mongo:
#    image: mongo
#    restart: always
#    environment:
#      MONGO_INITDB_ROOT_USERNAME: root
#      MONGO_INITDB_ROOT_PASSWORD: example
#
#  mongo-express:
#    image: mongo-express
#    restart: always
#    ports:
#      - 8081:8081
#    environment:  # no esta tomando usr y pass
#      ME_CONFIG_MONGODB_ADMINUSERNAME: root
#      ME_CONFIG_MONGODB_ADMINPASSWORD: example
#    depends_on:
#      - mongo

  cache:
    image: memcached
    ports:
    - "11211:777"